import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import * as fcl from "@onflow/fcl";
import "../flow/config.js";
import { MINT_TIME } from "../flow/cadence/transactions/mintTime";
import ActionBox from "../components/ActionBox";
import ExpiredList from "../components/ExpiredList";
import TotalSupply from "../components/TotalSupply";
import NotExpiredList from "../components/NotExpiredList";
import Navbar from "../components/Navbar";

export default function Home() {
  const [User, setUser] = useState();

  useEffect(() => {
    fcl.currentUser.subscribe(setUser);
    console.log(User);
  }, []);

  const handleMint = async (hour) => {
    try {
      const txid = await fcl.mutate({
        cadence: MINT_TIME,
        args: (arg, t) => [
          arg("n1", t.String),
          arg("n2", t.String),
          arg("n3", t.String),
          arg("n4", t.String),
          arg(hour, t.UInt64),
        ],

        limit: 999,
      });

      fcl.tx(txid).subscribe(({ status }) => {
        console.log("status", status);
      });

      console.log("txid", txid);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>Conditional NFTs</h1>
        <p className={styles.description}>{User && User.addr}</p>
        <TotalSupply />

        <ActionBox title="Mint NFT" fn={handleMint} />

        <ExpiredList />
        <NotExpiredList />
      </main>
    </div>
  );
}
